# =============================================================================
# check_setup.py
# Run this before inference to verify everything is in place.
# Usage: python check_setup.py
# =============================================================================

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import (
    DATASET_DIR, LANDMARKS_CSV, MODEL_KERAS_PATH,
    MODEL_TFLITE_PATH, LABEL_MAP_PATH, SCALER_PATH, GESTURE_LABELS,
)

PASS = "  ✅"
FAIL = "  ❌"
WARN = "  ⚠️ "

def check(label, condition, required=True):
    icon = PASS if condition else (FAIL if required else WARN)
    print(f"{icon}  {label}")
    return condition

print("\n🤙  Sign Language Translator – Setup Check\n" + "=" * 50)

# ── Step 1: Dataset ───────────────────────────────────────────────────────────
print("\n[Step 1] Dataset (collect_data.py)")
dataset_ok = True
for gesture in GESTURE_LABELS:
    folder = os.path.join(DATASET_DIR, gesture)
    count  = len(os.listdir(folder)) if os.path.isdir(folder) else 0
    ok     = check(f"{gesture:<20} {count} images", count >= 100)
    if not ok:
        dataset_ok = False

# ── Step 2: Landmarks ─────────────────────────────────────────────────────────
print("\n[Step 2] Preprocessing (preprocess.py)")
check("landmarks.csv exists", os.path.exists(LANDMARKS_CSV))

# ── Step 3: Model files ───────────────────────────────────────────────────────
print("\n[Step 3] Training (train_model.py)")
check("gesture_model.keras", os.path.exists(MODEL_KERAS_PATH))
check("scaler.pkl",          os.path.exists(SCALER_PATH))
check("label_map.json",      os.path.exists(LABEL_MAP_PATH))

# ── Step 4: TFLite ────────────────────────────────────────────────────────────
print("\n[Step 4] Conversion (convert_tflite.py)")
check("gesture_model.tflite", os.path.exists(MODEL_TFLITE_PATH))

# ── Step 5: Docs plots ────────────────────────────────────────────────────────
print("\n[Step 5] Training plots (generated by train_model.py)")
for plot in ["accuracy_plot.png", "loss_plot.png", "confusion_matrix.png"]:
    path = os.path.join(os.path.dirname(__file__), "docs", plot)
    check(plot, os.path.exists(path), required=False)

# ── Summary ───────────────────────────────────────────────────────────────────
tflite_ready = os.path.exists(MODEL_TFLITE_PATH) and os.path.exists(LABEL_MAP_PATH) and os.path.exists(SCALER_PATH)
print("\n" + "=" * 50)
if tflite_ready:
    print("✅  Ready to run!  Use:")
    print("    streamlit run app.py")
    print("    python inference.py")
else:
    print("❌  Not ready. Follow the steps above in order:")
    if not dataset_ok:
        print("    → python collect_data.py")
    if not os.path.exists(LANDMARKS_CSV):
        print("    → python preprocess.py")
    if not os.path.exists(MODEL_KERAS_PATH):
        print("    → python train_model.py")
    if not os.path.exists(MODEL_TFLITE_PATH):
        print("    → python convert_tflite.py")
print()
